spring:
  config:
    import: "aws-parameterstore:/cloud-project-app/prod/"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      # validate : 데이터베이스내부 테이블과 entity(코드)가 일치한지 검증.
      ddl-auto: validate
#      ddl-auto: none
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${BUCKETNAME}

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    message: ${APP_MESSAGE}

logging:
  level:
    root: INFO